### PR TITLE
add ArgumentParser description

### PR DESCRIPTION
**Pull request by sridwan**
Hi, you have a very useful library.

With this merge the description will be printed when showing help.
The test still pass.

### CODE REVIEW

**Comment by nhoffman** [comment]
Hi @sridwan - thanks a lot for the contribution! This change does not seem to be backward-compatible with scripts that invoke the ``argparse`` function without a description argument. Can you think of a way to make the description optional?

**Comment by sridwan** [comment]
How about we use environment variable ARGPARSE_DESCRIPTION ?
Those who want to add description just add the line `ARGPARSE_DESCRIPTION="Test description"` before sourcing argparse.bash.

It won't change the behavior of existing script that don't have the variable.

**Comment by nhoffman** [comment]
An environment variable sounds like a good solution to me.

**Comment by nhoffman** [comment]
Looks great, thank you! My only change was to wrap the description in triple quotes to protect against line breaks. One thing that I can't figure out is why you are not listed as a contributor after the merge... I  do see your commits in my repo.

**Comment by sridwan** [comment]
No problem, happy to contribute :smile:

**Pull request merged**
